apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-ce-deployment
spec:
  selector:
    matchLabels:
      app: gitlab-ce
  template:
    metadata:
      labels:
        app: gitlab-ce
    spec:
      containers:
      - name: gitlab-ce-container
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    targetPort: 80
